name: Run Cypress tests

on:
  workflow_run:
    workflows: ["Deploy to Production"]
    types:
      - completed

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          VUE_APP_CLIENT_ID: ${{secrets.VUE_APP_CLIENT_ID}}
          VUE_APP_API_URL: ${{secrets.VUE_APP_API_URL}}
          VUE_APP_CLIENT_URL: https://tutorial.eaglesoftwareteam.com
          VUE_APP_CLIENT_SECRET: ${{secrets.VUE_APP_CLIENT_SECRET}}
          VUE_APP_REFRESH_TOKEN: ${{secrets.VUE_APP_REFRESH_TOKEN}}
        with:
          build: npx cypress info
          config: baseUrl=https://tutorial.eaglesoftwareteam.com/tutorial-frontend-vue2
          headed: true
