name: Deploy to Production

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  aws-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      VUE_APP_CLIENT_ID: ${{secrets.VUE_APP_CLIENT_ID}}
      VUE_APP_API_URL: ${{secrets.VUE_APP_API_URL}}
      VUE_APP_CLIENT_URL: ${{secrets.VUE_APP_CLIENT_URL}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          touch .env
          echo VUE_APP_CLIENT_ID="$VUE_APP_CLIENT_ID" >> .env
          echo VUE_APP_API_URL="$VUE_APP_API_URL" >> .env
          echo VUE_APP_CLIENT_URL="https://project3.eaglesoftwareteam.com" >> .env
          echo VUE_APP_SITE_URL="https://project3.eaglesoftwareteam.com" >> .env

      - run: npm install
      - run: npm run build
      - run: npm run bundle

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: "project3.eaglesoftwareteam.com"
          REMOTE_USER: ubuntu
          TARGET: "/var/www/html/sev2026/t8"

      - name: Post-deploy remote commands
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: "ubuntu@project3.eaglesoftwareteam.com"
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          debug: false
          command: |
            sudo chown -R www-data:www-data /var/www/html/sev2026/t8 || true
            sudo chmod -R 755 /var/www/html/sev2026/t8 || true
            sudo systemctl reload nginx || true
